#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "../include/parser.h"
#include "../include/codegen.h"
#include "../include/vm.h"
#include "../include/ir.h"
#include "../include/logger.h"
#include "../include/bootstrap.h"
#include "../include/selfhost.h"
#include "../include/verilog_emit.h"

int main(int argc, char **argv) {
    logger_init("logs/compiler.log");
    LOG_INFO_MSG("Main", "TASK-006", "Compiler started");

    if (argc < 2) {
        printf("Usage: %s [--self-host | --self-host-full | --emit-verilog <source> <out.v> | <c_source>]\n", argv[0]);
        return 1;
    }

    /* Self-host mode: compile own source subset and run on VM */
    if (strcmp(argv[1], "--self-host") == 0) {
        LOG_INFO_MSG("Main", "TASK-018", "Self-host mode entered");
        int result = bootstrap_self_test();
        LOG_INFO_MSG("Main", "TASK-018", result == 0 ? "Self-host PASS" : "Self-host FAIL");
        logger_close();
        return result;
    }

    /* Full self-hosting verification (Phase 5) */
    if (strcmp(argv[1], "--self-host-full") == 0) {
        LOG_INFO_MSG("Main", "Phase5", "Full self-hosting verification");
        int result = selfhost_full_test();
        LOG_INFO_MSG("Main", "Phase5", result == 0 ? "Self-host-full PASS" : "Self-host-full FAIL");
        logger_close();
        return result;
    }

    /* Verilog emission mode: compile to bytecode, then emit Verilog testbench */
    if (strcmp(argv[1], "--emit-verilog") == 0) {
        if (argc < 4) {
            printf("Usage: %s --emit-verilog <c_source> <output.v>\n", argv[0]);
            return 1;
        }
        LOG_INFO_MSG("Main", "TASK-017", "Verilog emission mode");
        tokenize(argv[2]);
        parse();
        codegen();
        int rc = emit_verilog_testbench(bytecode, (int)bc_idx, argv[3]);
        if (rc == 0) {
            printf("Emitted Verilog testbench to %s (%zu bytecode bytes)\n", argv[3], bc_idx);
        } else {
            fprintf(stderr, "Failed to write Verilog to %s\n", argv[3]);
        }
        logger_close();
        return rc;
    }

    const char *source = argv[1];

    printf("Compiling: %s\n", source);

    tokenize(source);
    parse();
    codegen();

    printf("Generated %zu bytes of bytecode\n", bc_idx);

    // Run the generated bytecode on the ternary VM
    vm_run(bytecode, bc_idx);

    LOG_INFO_MSG("Main", "TASK-006", "Compiler finished");
    logger_close();
    return 0;
}
